[build]
command = "npm run build"
publish = "build/client"
environment = { NODE_VERSION = "22" }

[dev]
command = "npm run dev"
targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
